<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SharedDataverseLogic</RootNamespace>
    <TargetFramework></TargetFramework>
    <TargetFrameworks>net462;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>
</Project>
