//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xrm.Sdk.Client;
using System.Runtime.Serialization;

[assembly: ProxyTypesAssembly()]


namespace XrmBedrock.SharedContext {
    
    
    [DataContract()]
    public enum powerpagelanguages {
        
        [EnumMember()]
        [OptionSetMetadata("Arabic", Index=0, Lcid=1033, Description="", Color="#0000ff")]
        Arabic = 1025,
        
        [EnumMember()]
        [OptionSetMetadata("Bulgarian - Bulgaria", Index=2, Lcid=1033, Description="", Color="#0000ff")]
        BulgarianBulgaria = 1026,
        
        [EnumMember()]
        [OptionSetMetadata("Catalan - Catalan", Index=3, Lcid=1033, Description="", Color="#0000ff")]
        CatalanCatalan = 1027,
        
        [EnumMember()]
        [OptionSetMetadata("Chinese - Traditional", Index=6, Lcid=1033, Description="", Color="#0000ff")]
        ChineseTraditional = 1028,
        
        [EnumMember()]
        [OptionSetMetadata("Czech - Czech Republic", Index=8, Lcid=1033, Description="", Color="#0000ff")]
        CzechCzechRepublic = 1029,
        
        [EnumMember()]
        [OptionSetMetadata("Danish - Denmark", Index=9, Lcid=1033, Description="", Color="#0000ff")]
        DanishDenmark = 1030,
        
        [EnumMember()]
        [OptionSetMetadata("German - Germany", Index=16, Lcid=1033, Description="", Color="#0000ff")]
        GermanGermany = 1031,
        
        [EnumMember()]
        [OptionSetMetadata("Greek - Greece", Index=17, Lcid=1033, Description="", Color="#0000ff")]
        GreekGreece = 1032,
        
        [EnumMember()]
        [OptionSetMetadata("English", Index=11, Lcid=1033, Description="", Color="#0000ff")]
        English = 1033,
        
        [EnumMember()]
        [OptionSetMetadata("Finnish - Finland", Index=13, Lcid=1033, Description="", Color="#0000ff")]
        FinnishFinland = 1035,
        
        [EnumMember()]
        [OptionSetMetadata("French - France", Index=14, Lcid=1033, Description="", Color="#0000ff")]
        FrenchFrance = 1036,
        
        [EnumMember()]
        [OptionSetMetadata("Hebrew", Index=18, Lcid=1033, Description="", Color="#0000ff")]
        Hebrew = 1037,
        
        [EnumMember()]
        [OptionSetMetadata("Hungarian - Hungary", Index=20, Lcid=1033, Description="", Color="#0000ff")]
        HungarianHungary = 1038,
        
        [EnumMember()]
        [OptionSetMetadata("Italian - Italy", Index=22, Lcid=1033, Description="", Color="#0000ff")]
        ItalianItaly = 1040,
        
        [EnumMember()]
        [OptionSetMetadata("Japanese - Japan", Index=23, Lcid=1033, Description="", Color="#0000ff")]
        JapaneseJapan = 1041,
        
        [EnumMember()]
        [OptionSetMetadata("Korean - Korea", Index=25, Lcid=1033, Description="", Color="#0000ff")]
        KoreanKorea = 1042,
        
        [EnumMember()]
        [OptionSetMetadata("Dutch - Netherlands", Index=10, Lcid=1033, Description="", Color="#0000ff")]
        DutchNetherlands = 1043,
        
        [EnumMember()]
        [OptionSetMetadata("Norwegian (Bokmål) - Norway", Index=29, Lcid=1033, Description="", Color="#0000ff")]
        NorwegianBokmålNorway = 1044,
        
        [EnumMember()]
        [OptionSetMetadata("Polish - Poland", Index=30, Lcid=1033, Description="", Color="#0000ff")]
        PolishPoland = 1045,
        
        [EnumMember()]
        [OptionSetMetadata("Portuguese - Brazil", Index=31, Lcid=1033, Description="", Color="#0000ff")]
        PortugueseBrazil = 1046,
        
        [EnumMember()]
        [OptionSetMetadata("Romanian - Romania", Index=33, Lcid=1033, Description="", Color="#0000ff")]
        RomanianRomania = 1048,
        
        [EnumMember()]
        [OptionSetMetadata("Russian - Russia", Index=34, Lcid=1033, Description="", Color="#0000ff")]
        RussianRussia = 1049,
        
        [EnumMember()]
        [OptionSetMetadata("Croatian - Croatia", Index=7, Lcid=1033, Description="", Color="#0000ff")]
        CroatianCroatia = 1050,
        
        [EnumMember()]
        [OptionSetMetadata("Slovak - Slovakia", Index=37, Lcid=1033, Description="", Color="#0000ff")]
        SlovakSlovakia = 1051,
        
        [EnumMember()]
        [OptionSetMetadata("Swedish - Sweden", Index=40, Lcid=1033, Description="", Color="#0000ff")]
        SwedishSweden = 1053,
        
        [EnumMember()]
        [OptionSetMetadata("Thai - Thailand", Index=41, Lcid=1033, Description="", Color="#0000ff")]
        ThaiThailand = 1054,
        
        [EnumMember()]
        [OptionSetMetadata("Turkish - Türkiye", Index=42, Lcid=1033, Description="", Color="#0000ff")]
        TurkishTürkiye = 1055,
        
        [EnumMember()]
        [OptionSetMetadata("Indonesian - Indonesia", Index=21, Lcid=1033, Description="", Color="#0000ff")]
        IndonesianIndonesia = 1057,
        
        [EnumMember()]
        [OptionSetMetadata("Ukrainian - Ukraine", Index=43, Lcid=1033, Description="", Color="#0000ff")]
        UkrainianUkraine = 1058,
        
        [EnumMember()]
        [OptionSetMetadata("Slovenian - Slovenia", Index=38, Lcid=1033, Description="", Color="#0000ff")]
        SlovenianSlovenia = 1060,
        
        [EnumMember()]
        [OptionSetMetadata("Estonian - Estonia", Index=12, Lcid=1033, Description="", Color="#0000ff")]
        EstonianEstonia = 1061,
        
        [EnumMember()]
        [OptionSetMetadata("Latvian - Latvia", Index=26, Lcid=1033, Description="", Color="#0000ff")]
        LatvianLatvia = 1062,
        
        [EnumMember()]
        [OptionSetMetadata("Lithuanian - Lithuania", Index=27, Lcid=1033, Description="", Color="#0000ff")]
        LithuanianLithuania = 1063,
        
        [EnumMember()]
        [OptionSetMetadata("Vietnamese - Vietnam", Index=44, Lcid=1033, Description="", Color="#0000ff")]
        VietnameseVietnam = 1066,
        
        [EnumMember()]
        [OptionSetMetadata("Basque - Basque", Index=1, Lcid=1033, Description="", Color="#0000ff")]
        BasqueBasque = 1069,
        
        [EnumMember()]
        [OptionSetMetadata("Hindi - India", Index=19, Lcid=1033, Description="", Color="#0000ff")]
        HindiIndia = 1081,
        
        [EnumMember()]
        [OptionSetMetadata("Malay - Malaysia", Index=28, Lcid=1033, Description="", Color="#0000ff")]
        MalayMalaysia = 1086,
        
        [EnumMember()]
        [OptionSetMetadata("Kazakh - Kazakhstan", Index=24, Lcid=1033, Description="", Color="#0000ff")]
        KazakhKazakhstan = 1087,
        
        [EnumMember()]
        [OptionSetMetadata("Galician - Spain", Index=15, Lcid=1033, Description="", Color="#0000ff")]
        GalicianSpain = 1110,
        
        [EnumMember()]
        [OptionSetMetadata("Chinese - China", Index=4, Lcid=1033, Description="", Color="#0000ff")]
        ChineseChina = 2052,
        
        [EnumMember()]
        [OptionSetMetadata("Portuguese - Portugal", Index=32, Lcid=1033, Description="", Color="#0000ff")]
        PortuguesePortugal = 2070,
        
        [EnumMember()]
        [OptionSetMetadata("Serbian (Latin) - Serbia", Index=36, Lcid=1033, Description="", Color="#0000ff")]
        SerbianLatinSerbia = 2074,
        
        [EnumMember()]
        [OptionSetMetadata("Chinese - Hong Kong SAR", Index=5, Lcid=1033, Description="", Color="#0000ff")]
        ChineseHongKongSAR = 3076,
        
        [EnumMember()]
        [OptionSetMetadata("Spanish (Traditional Sort) - Spain", Index=39, Lcid=1033, Description="", Color="#0000ff")]
        SpanishTraditionalSortSpain = 3082,
        
        [EnumMember()]
        [OptionSetMetadata("Serbian (Cyrillic) - Serbia", Index=35, Lcid=1033, Description="", Color="#0000ff")]
        SerbianCyrillicSerbia = 3098,
    }
    
    [DataContract()]
    public enum componentstate {
        
        [EnumMember()]
        [OptionSetMetadata("Published", Index=0, Lcid=1033)]
        Published = 0,
        
        [EnumMember()]
        [OptionSetMetadata("Unpublished", Index=1, Lcid=1033)]
        Unpublished = 1,
        
        [EnumMember()]
        [OptionSetMetadata("Deleted", Index=2, Lcid=1033)]
        Deleted = 2,
        
        [EnumMember()]
        [OptionSetMetadata("Deleted Unpublished", Index=3, Lcid=1033)]
        DeletedUnpublished = 3,
    }
    
    [DataContract()]
    public enum msdyn_queueassignmentstrategy {
        
        [EnumMember()]
        [OptionSetMetadata("Omnichannel Assignment", Index=0, Lcid=1033, Description="", Color="#0000ff")]
        OmnichannelAssignment = 192350000,
        
        [EnumMember()]
        [OptionSetMetadata("Round Robin", Index=1, Lcid=1033, Description="", Color="#0000ff")]
        RoundRobin = 192350001,
        
        [EnumMember()]
        [OptionSetMetadata("Custom Assignment Configuration", Index=2, Lcid=1033, Description="", Color="#0000ff")]
        CustomAssignmentConfiguration = 192350002,
        
        [EnumMember()]
        [OptionSetMetadata("Longest Idle", Index=3, Lcid=1033, Description="", Color="#0000ff")]
        LongestIdle = 192350003,
    }
    
    [DataContract()]
    public enum msdyn_queuetype {
        
        [EnumMember()]
        [OptionSetMetadata("Messaging", Index=0, Lcid=1033, Color="#0000ff")]
        Messaging = 192350000,
        
        [EnumMember()]
        [OptionSetMetadata("Entity", Index=1, Lcid=1033, Color="#0000ff")]
        Entity = 192350001,
    }
    
    [DataContract()]
    public enum activitypointer_activitytypecode {
        
        [EnumMember()]
        [OptionSetMetadata("Appointment", Index=4, Lcid=1033)]
        Appointment = 4201,
        
        [EnumMember()]
        [OptionSetMetadata("Email", Index=2, Lcid=1033)]
        Email = 4202,
        
        [EnumMember()]
        [OptionSetMetadata("Fax", Index=0, Lcid=1033)]
        Fax = 4204,
        
        [EnumMember()]
        [OptionSetMetadata("Case Resolution", Index=13, Lcid=1033)]
        CaseResolution = 4206,
        
        [EnumMember()]
        [OptionSetMetadata("Letter", Index=3, Lcid=1033)]
        Letter = 4207,
        
        [EnumMember()]
        [OptionSetMetadata("Opportunity Close", Index=15, Lcid=1033)]
        OpportunityClose = 4208,
        
        [EnumMember()]
        [OptionSetMetadata("Order Close", Index=16, Lcid=1033)]
        OrderClose = 4209,
        
        [EnumMember()]
        [OptionSetMetadata("Phone Call", Index=1, Lcid=1033)]
        PhoneCall = 4210,
        
        [EnumMember()]
        [OptionSetMetadata("Quote Close", Index=17, Lcid=1033)]
        QuoteClose = 4211,
        
        [EnumMember()]
        [OptionSetMetadata("Task", Index=5, Lcid=1033)]
        Task = 4212,
        
        [EnumMember()]
        [OptionSetMetadata("Service Activity", Index=14, Lcid=1033)]
        ServiceActivity = 4214,
        
        [EnumMember()]
        [OptionSetMetadata("Recurring Appointment", Index=6, Lcid=1033)]
        RecurringAppointment = 4251,
        
        [EnumMember()]
        [OptionSetMetadata("Campaign Response", Index=12, Lcid=1033)]
        CampaignResponse = 4401,
        
        [EnumMember()]
        [OptionSetMetadata("Campaign Activity", Index=11, Lcid=1033)]
        CampaignActivity = 4402,
        
        [EnumMember()]
        [OptionSetMetadata("Quick Campaign", Index=10, Lcid=1033)]
        QuickCampaign = 4406,
        
        [EnumMember()]
        [OptionSetMetadata("Teams chat", Index=7, Lcid=1033)]
        Teamschat = 10199,
        
        [EnumMember()]
        [OptionSetMetadata("Invite Redemption", Index=8, Lcid=1033)]
        InviteRedemption = 10329,
        
        [EnumMember()]
        [OptionSetMetadata("Portal Comment", Index=9, Lcid=1033)]
        PortalComment = 10330,
        
        [EnumMember()]
        [OptionSetMetadata("Customer Voice alert", Index=18, Lcid=1033)]
        CustomerVoicealert = 10622,
        
        [EnumMember()]
        [OptionSetMetadata("Customer Voice survey invite", Index=19, Lcid=1033)]
        CustomerVoicesurveyinvite = 10632,
        
        [EnumMember()]
        [OptionSetMetadata("Customer Voice survey response", Index=20, Lcid=1033)]
        CustomerVoicesurveyresponse = 10634,
        
        [EnumMember()]
        [OptionSetMetadata("Conversation", Index=21, Lcid=1033)]
        Conversation = 10717,
        
        [EnumMember()]
        [OptionSetMetadata("Session", Index=22, Lcid=1033)]
        Session = 10734,
        
        [EnumMember()]
        [OptionSetMetadata("Copilot Transcript", Index=23, Lcid=1033)]
        CopilotTranscript = 10919,
    }
    
    [DataContract()]
    public enum mgs_billinginterval {
        
        [EnumMember()]
        [OptionSetMetadata("Yearly", Index=0, Lcid=1033, Description="")]
        Yearly = 862810000,
        
        [EnumMember()]
        [OptionSetMetadata("Monthly", Index=1, Lcid=1033, Description="")]
        Monthly = 862810001,
    }
    
    [DataContract()]
    public enum mgs_transactiontype {
        
        [EnumMember()]
        [OptionSetMetadata("Product", Index=0, Lcid=1033, Description="")]
        Product = 862810000,
        
        [EnumMember()]
        [OptionSetMetadata("Credit", Index=1, Lcid=1033, Description="")]
        Credit = 862810001,
    }
}
