//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace XrmBedrock.SharedContext {
    
    
    public interface ICustomer : IEntity {
        
        Guid? Address1_AddressId {
            get;
            set;
        }
        
        string Address1_City {
            get;
            set;
        }
        
        string Address1_Composite {
            get;
        }
        
        string Address1_Country {
            get;
            set;
        }
        
        string Address1_County {
            get;
            set;
        }
        
        string Address1_Fax {
            get;
            set;
        }
        
        double? Address1_Latitude {
            get;
            set;
        }
        
        string Address1_Line1 {
            get;
            set;
        }
        
        string Address1_Line2 {
            get;
            set;
        }
        
        string Address1_Line3 {
            get;
            set;
        }
        
        double? Address1_Longitude {
            get;
            set;
        }
        
        string Address1_Name {
            get;
            set;
        }
        
        string Address1_PostalCode {
            get;
            set;
        }
        
        string Address1_PostOfficeBox {
            get;
            set;
        }
        
        string Address1_PrimaryContactName {
            get;
            set;
        }
        
        string Address1_StateOrProvince {
            get;
            set;
        }
        
        string Address1_Telephone1 {
            get;
            set;
        }
        
        string Address1_Telephone2 {
            get;
            set;
        }
        
        string Address1_Telephone3 {
            get;
            set;
        }
        
        string Address1_UPSZone {
            get;
            set;
        }
        
        int? Address1_UTCOffset {
            get;
            set;
        }
        
        Guid? Address2_AddressId {
            get;
            set;
        }
        
        string Address2_City {
            get;
            set;
        }
        
        string Address2_Composite {
            get;
        }
        
        string Address2_Country {
            get;
            set;
        }
        
        string Address2_County {
            get;
            set;
        }
        
        string Address2_Fax {
            get;
            set;
        }
        
        double? Address2_Latitude {
            get;
            set;
        }
        
        string Address2_Line1 {
            get;
            set;
        }
        
        string Address2_Line2 {
            get;
            set;
        }
        
        string Address2_Line3 {
            get;
            set;
        }
        
        double? Address2_Longitude {
            get;
            set;
        }
        
        string Address2_Name {
            get;
            set;
        }
        
        string Address2_PostalCode {
            get;
            set;
        }
        
        string Address2_PostOfficeBox {
            get;
            set;
        }
        
        string Address2_PrimaryContactName {
            get;
            set;
        }
        
        string Address2_StateOrProvince {
            get;
            set;
        }
        
        string Address2_Telephone1 {
            get;
            set;
        }
        
        string Address2_Telephone2 {
            get;
            set;
        }
        
        string Address2_Telephone3 {
            get;
            set;
        }
        
        string Address2_UPSZone {
            get;
            set;
        }
        
        int? Address2_UTCOffset {
            get;
            set;
        }
        
        string Adx_CreatedByIPAddress {
            get;
            set;
        }
        
        string Adx_CreatedByUsername {
            get;
            set;
        }
        
        string Adx_ModifiedByIPAddress {
            get;
            set;
        }
        
        string Adx_ModifiedByUsername {
            get;
            set;
        }
        
        decimal? Aging30 {
            get;
        }
        
        decimal? Aging30_Base {
            get;
        }
        
        decimal? Aging60 {
            get;
        }
        
        decimal? Aging60_Base {
            get;
        }
        
        decimal? Aging90 {
            get;
        }
        
        decimal? Aging90_Base {
            get;
        }
        
        EntityReference CreatedBy {
            get;
        }
        
        EntityReference CreatedByExternalParty {
            get;
        }
        
        DateTime? CreatedOn {
            get;
        }
        
        EntityReference CreatedOnBehalfBy {
            get;
        }
        
        decimal? CreditLimit {
            get;
            set;
        }
        
        decimal? CreditLimit_Base {
            get;
        }
        
        bool? CreditOnHold {
            get;
            set;
        }
        
        EntityReference DefaultPriceLevelId {
            get;
            set;
        }
        
        string Description {
            get;
            set;
        }
        
        bool? DoNotBulkEMail {
            get;
            set;
        }
        
        bool? DoNotBulkPostalMail {
            get;
            set;
        }
        
        bool? DoNotEMail {
            get;
            set;
        }
        
        bool? DoNotFax {
            get;
            set;
        }
        
        bool? DoNotPhone {
            get;
            set;
        }
        
        bool? DoNotPostalMail {
            get;
            set;
        }
        
        bool? DoNotSendMM {
            get;
            set;
        }
        
        string EMailAddress1 {
            get;
            set;
        }
        
        string EMailAddress2 {
            get;
            set;
        }
        
        string EMailAddress3 {
            get;
            set;
        }
        
        Guid? EntityImageId {
            get;
        }
        
        decimal? ExchangeRate {
            get;
        }
        
        string Fax {
            get;
            set;
        }
        
        bool? FollowEmail {
            get;
            set;
        }
        
        int? ImportSequenceNumber {
            get;
            set;
        }
        
        DateTime? LastOnHoldTime {
            get;
            set;
        }
        
        DateTime? LastUsedInCampaign {
            get;
            set;
        }
        
        bool? MarketingOnly {
            get;
            set;
        }
        
        EntityReference MasterId {
            get;
        }
        
        bool? Merged {
            get;
        }
        
        EntityReference ModifiedBy {
            get;
        }
        
        EntityReference ModifiedByExternalParty {
            get;
        }
        
        DateTime? ModifiedOn {
            get;
        }
        
        EntityReference ModifiedOnBehalfBy {
            get;
        }
        
        EntityReference msa_managingpartnerid {
            get;
            set;
        }
        
        bool? msdyn_gdproptout {
            get;
            set;
        }
        
        int? msdyn_PrimaryTimeZone {
            get;
            set;
        }
        
        EntityReference msdyn_segmentid {
            get;
            set;
        }
        
        int? OnHoldTime {
            get;
        }
        
        EntityReference OriginatingLeadId {
            get;
            set;
        }
        
        DateTime? OverriddenCreatedOn {
            get;
            set;
        }
        
        EntityReference OwnerId {
            get;
            set;
        }
        
        EntityReference OwningBusinessUnit {
            get;
        }
        
        EntityReference OwningTeam {
            get;
        }
        
        EntityReference OwningUser {
            get;
        }
        
        bool? ParticipatesInWorkflow {
            get;
            set;
        }
        
        EntityReference PreferredEquipmentId {
            get;
            set;
        }
        
        EntityReference PreferredServiceId {
            get;
            set;
        }
        
        EntityReference PreferredSystemUserId {
            get;
            set;
        }
        
        Guid? ProcessId {
            get;
            set;
        }
        
        EntityReference SLAId {
            get;
            set;
        }
        
        EntityReference SLAInvokedId {
            get;
        }
        
        Guid? StageId {
            get;
            set;
        }
        
        int? TeamsFollowed {
            get;
            set;
        }
        
        string Telephone1 {
            get;
            set;
        }
        
        string Telephone2 {
            get;
            set;
        }
        
        string Telephone3 {
            get;
            set;
        }
        
        string TimeSpentByMeOnEmailAndMeetings {
            get;
        }
        
        int? TimeZoneRuleVersionNumber {
            get;
            set;
        }
        
        EntityReference TransactionCurrencyId {
            get;
            set;
        }
        
        string TraversedPath {
            get;
            set;
        }
        
        int? UTCConversionTimeZoneCode {
            get;
            set;
        }
        
        long? VersionNumber {
            get;
        }
    }
}
