//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace XrmBedrock.SharedContext {
    
    
    /// <summary>
    /// <para>This table contains records of transaction information</para>
    /// <para>Display Name: Transaction</para>
    /// </summary>
    [EntityLogicalName("mgs_transaction")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class mgs_Transaction : ExtendedEntity<mgs_TransactionState, mgs_Transaction_statuscode> {
        
        public const string EntityLogicalName = "mgs_transaction";
        
        public const int EntityTypeCode = 11143;
        
        public mgs_Transaction() : 
                base(EntityLogicalName) {
        }
        
        public mgs_Transaction(Guid Id) : 
                base(EntityLogicalName, Id) {
        }
        
        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay("mgs_transaction1");
            }
        }
        
        [AttributeLogicalName("mgs_transactionid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("mgs_transactionid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for entity instances</para>
        /// <para>Display Name: Transaction</para>
        /// </summary>
        [AttributeLogicalName("mgs_transactionid")]
        [DisplayName("Transaction")]
        public Guid? mgs_TransactionId {
            get {
                return GetAttributeValue<Guid?>("mgs_transactionid");
            }
            set {
                SetId("mgs_transactionid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who created the record.</para>
        /// <para>Display Name: Created By</para>
        /// </summary>
        [AttributeLogicalName("createdby")]
        [DisplayName("Created By")]
        public EntityReference CreatedBy {
            get {
                return GetAttributeValue<EntityReference>("createdby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the record was created.</para>
        /// <para>Display Name: Created On</para>
        /// </summary>
        [AttributeLogicalName("createdon")]
        [DisplayName("Created On")]
        public DateTime? CreatedOn {
            get {
                return GetAttributeValue<DateTime?>("createdon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who created the record.</para>
        /// <para>Display Name: Created By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfby")]
        [DisplayName("Created By (Delegate)")]
        public EntityReference CreatedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("createdonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Exchange rate for the currency associated with the entity with respect to the base currency.</para>
        /// <para>Display Name: Exchange Rate</para>
        /// </summary>
        [AttributeLogicalName("exchangerate")]
        [DisplayName("Exchange Rate")]
        public decimal? ExchangeRate {
            get {
                return GetAttributeValue<decimal?>("exchangerate");
            }
        }
        
        /// <summary>
        /// <para>Sequence number of the import that created this record.</para>
        /// <para>Display Name: Import Sequence Number</para>
        /// </summary>
        [AttributeLogicalName("importsequencenumber")]
        [DisplayName("Import Sequence Number")]
        [Range(-2147483648, 2147483647)]
        public int? ImportSequenceNumber {
            get {
                return GetAttributeValue<int?>("importsequencenumber");
            }
            set {
                SetAttributeValue("importsequencenumber", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who modified the record.</para>
        /// <para>Display Name: Modified By</para>
        /// </summary>
        [AttributeLogicalName("modifiedby")]
        [DisplayName("Modified By")]
        public EntityReference ModifiedBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the record was modified.</para>
        /// <para>Display Name: Modified On</para>
        /// </summary>
        [AttributeLogicalName("modifiedon")]
        [DisplayName("Modified On")]
        public DateTime? ModifiedOn {
            get {
                return GetAttributeValue<DateTime?>("modifiedon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who modified the record.</para>
        /// <para>Display Name: Modified By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfby")]
        [DisplayName("Modified By (Delegate)")]
        public EntityReference ModifiedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Date and time that the record was migrated.</para>
        /// <para>Display Name: Record Created On</para>
        /// </summary>
        [AttributeLogicalName("overriddencreatedon")]
        [DisplayName("Record Created On")]
        public DateTime? OverriddenCreatedOn {
            get {
                return GetAttributeValue<DateTime?>("overriddencreatedon");
            }
            set {
                SetAttributeValue("overriddencreatedon", value);
            }
        }
        
        /// <summary>
        /// <para>Owner Id</para>
        /// <para>Display Name: Owner</para>
        /// </summary>
        [AttributeLogicalName("ownerid")]
        [DisplayName("Owner")]
        public EntityReference OwnerId {
            get {
                return GetAttributeValue<EntityReference>("ownerid");
            }
            set {
                SetAttributeValue("ownerid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the business unit that owns the record</para>
        /// <para>Display Name: Owning Business Unit</para>
        /// </summary>
        [AttributeLogicalName("owningbusinessunit")]
        [DisplayName("Owning Business Unit")]
        public EntityReference OwningBusinessUnit {
            get {
                return GetAttributeValue<EntityReference>("owningbusinessunit");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the team that owns the record.</para>
        /// <para>Display Name: Owning Team</para>
        /// </summary>
        [AttributeLogicalName("owningteam")]
        [DisplayName("Owning Team")]
        public EntityReference OwningTeam {
            get {
                return GetAttributeValue<EntityReference>("owningteam");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the user that owns the record.</para>
        /// <para>Display Name: Owning User</para>
        /// </summary>
        [AttributeLogicalName("owninguser")]
        [DisplayName("Owning User")]
        public EntityReference OwningUser {
            get {
                return GetAttributeValue<EntityReference>("owninguser");
            }
        }
        
        /// <summary>
        /// <para>Display Name: Transaction</para>
        /// </summary>
        [AttributeLogicalName("mgs_transaction1")]
        [DisplayName("Transaction")]
        [MaxLength(850)]
        public string PrimaryNameField {
            get {
                return GetAttributeValue<string>("mgs_transaction1");
            }
            set {
                SetAttributeValue("mgs_transaction1", value);
            }
        }
        
        /// <summary>
        /// <para>For internal use only.</para>
        /// <para>Display Name: Time Zone Rule Version Number</para>
        /// </summary>
        [AttributeLogicalName("timezoneruleversionnumber")]
        [DisplayName("Time Zone Rule Version Number")]
        [Range(-1, 2147483647)]
        public int? TimeZoneRuleVersionNumber {
            get {
                return GetAttributeValue<int?>("timezoneruleversionnumber");
            }
            set {
                SetAttributeValue("timezoneruleversionnumber", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the currency associated with the entity.</para>
        /// <para>Display Name: Currency</para>
        /// </summary>
        [AttributeLogicalName("transactioncurrencyid")]
        [DisplayName("Currency")]
        public EntityReference TransactionCurrencyId {
            get {
                return GetAttributeValue<EntityReference>("transactioncurrencyid");
            }
            set {
                SetAttributeValue("transactioncurrencyid", value);
            }
        }
        
        /// <summary>
        /// <para>Time zone code that was in use when the record was created.</para>
        /// <para>Display Name: UTC Conversion Time Zone Code</para>
        /// </summary>
        [AttributeLogicalName("utcconversiontimezonecode")]
        [DisplayName("UTC Conversion Time Zone Code")]
        [Range(-1, 2147483647)]
        public int? UTCConversionTimeZoneCode {
            get {
                return GetAttributeValue<int?>("utcconversiontimezonecode");
            }
            set {
                SetAttributeValue("utcconversiontimezonecode", value);
            }
        }
        
        /// <summary>
        /// <para>Version Number</para>
        /// <para>Display Name: Version Number</para>
        /// </summary>
        [AttributeLogicalName("versionnumber")]
        [DisplayName("Version Number")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }
        
        /// <summary>
        /// <para>Display Name: Amount</para>
        /// </summary>
        [AttributeLogicalName("mgs_amount")]
        [DisplayName("Amount")]
        public decimal? mgs_Amount {
            get {
                return GetMoneyValue("mgs_amount");
            }
            set {
                SetMoneyValue("mgs_amount", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: End</para>
        /// </summary>
        [AttributeLogicalName("mgs_end")]
        [DisplayName("End")]
        public DateTime? mgs_End {
            get {
                return GetAttributeValue<DateTime?>("mgs_end");
            }
            set {
                SetAttributeValue("mgs_end", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Invoice</para>
        /// </summary>
        [AttributeLogicalName("mgs_invoice")]
        [DisplayName("Invoice")]
        public EntityReference mgs_Invoice {
            get {
                return GetAttributeValue<EntityReference>("mgs_invoice");
            }
            set {
                SetAttributeValue("mgs_invoice", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Start</para>
        /// </summary>
        [AttributeLogicalName("mgs_start")]
        [DisplayName("Start")]
        public DateTime? mgs_Start {
            get {
                return GetAttributeValue<DateTime?>("mgs_start");
            }
            set {
                SetAttributeValue("mgs_start", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Subscription</para>
        /// </summary>
        [AttributeLogicalName("mgs_subscription")]
        [DisplayName("Subscription")]
        public EntityReference mgs_Subscription {
            get {
                return GetAttributeValue<EntityReference>("mgs_subscription");
            }
            set {
                SetAttributeValue("mgs_subscription", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Transaction</para>
        /// </summary>
        [AttributeLogicalName("mgs_transaction1")]
        [DisplayName("Transaction")]
        [MaxLength(850)]
        public string mgs_Transaction1 {
            get {
                return GetAttributeValue<string>("mgs_transaction1");
            }
            set {
                SetAttributeValue("mgs_transaction1", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Type</para>
        /// </summary>
        [AttributeLogicalName("mgs_type")]
        [DisplayName("Type")]
        public mgs_transactiontype? mgs_Type {
            get {
                return GetOptionSetValue<mgs_transactiontype>("mgs_type");
            }
            set {
                SetOptionSetValue("mgs_type", value);
            }
        }
        
        /// <summary>
        /// <para>Value of the Amount in base currency.</para>
        /// <para>Display Name: Amount (Base)</para>
        /// </summary>
        [AttributeLogicalName("mgs_amount_base")]
        [DisplayName("Amount (Base)")]
        public decimal? mgs_amount_Base {
            get {
                return GetMoneyValue("mgs_amount_base");
            }
        }
        
        /// <summary>
        /// <para>Status of the Transaction</para>
        /// <para>Display Name: Status</para>
        /// </summary>
        [AttributeLogicalName("statecode")]
        [DisplayName("Status")]
        public mgs_TransactionState? statecode {
            get {
                return GetOptionSetValue<mgs_TransactionState>("statecode");
            }
            set {
                SetOptionSetValue("statecode", value);
            }
        }
        
        /// <summary>
        /// <para>Reason for the status of the Transaction</para>
        /// <para>Display Name: Status Reason</para>
        /// </summary>
        [AttributeLogicalName("statuscode")]
        [DisplayName("Status Reason")]
        public mgs_Transaction_statuscode? statuscode {
            get {
                return GetOptionSetValue<mgs_Transaction_statuscode>("statuscode");
            }
            set {
                SetOptionSetValue("statuscode", value);
            }
        }
        
        [AttributeLogicalName("createdby")]
        [RelationshipSchemaName("lk_mgs_transaction_createdby")]
        public SystemUser lk_mgs_transaction_createdby {
            get {
                return GetRelatedEntity<SystemUser>("lk_mgs_transaction_createdby", null);
            }
            set {
                SetRelatedEntity("lk_mgs_transaction_createdby", null, value);
            }
        }
        
        [AttributeLogicalName("createdonbehalfby")]
        [RelationshipSchemaName("lk_mgs_transaction_createdonbehalfby")]
        public SystemUser lk_mgs_transaction_createdonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_mgs_transaction_createdonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_mgs_transaction_createdonbehalfby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedby")]
        [RelationshipSchemaName("lk_mgs_transaction_modifiedby")]
        public SystemUser lk_mgs_transaction_modifiedby {
            get {
                return GetRelatedEntity<SystemUser>("lk_mgs_transaction_modifiedby", null);
            }
            set {
                SetRelatedEntity("lk_mgs_transaction_modifiedby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedonbehalfby")]
        [RelationshipSchemaName("lk_mgs_transaction_modifiedonbehalfby")]
        public SystemUser lk_mgs_transaction_modifiedonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_mgs_transaction_modifiedonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_mgs_transaction_modifiedonbehalfby", null, value);
            }
        }
        
        [RelationshipSchemaName("mgs_transaction_Annotations")]
        public IEnumerable<Annotation> mgs_transaction_Annotations {
            get {
                return GetRelatedEntities<Annotation>("mgs_transaction_Annotations", null);
            }
            set {
                SetRelatedEntities("mgs_transaction_Annotations", null, value);
            }
        }
        
        [AttributeLogicalName("mgs_invoice")]
        [RelationshipSchemaName("mgs_transaction_Invoice_mgs_invoice")]
        public mgs_Invoice mgs_transaction_Invoice_mgs_invoice {
            get {
                return GetRelatedEntity<mgs_Invoice>("mgs_transaction_Invoice_mgs_invoice", null);
            }
            set {
                SetRelatedEntity("mgs_transaction_Invoice_mgs_invoice", null, value);
            }
        }
        
        [AttributeLogicalName("mgs_subscription")]
        [RelationshipSchemaName("mgs_transaction_Subscription_mgs_subscription")]
        public mgs_Subscription mgs_transaction_Subscription_mgs_subscription {
            get {
                return GetRelatedEntity<mgs_Subscription>("mgs_transaction_Subscription_mgs_subscription", null);
            }
            set {
                SetRelatedEntity("mgs_transaction_Subscription_mgs_subscription", null, value);
            }
        }
        
        [AttributeLogicalName("owninguser")]
        [RelationshipSchemaName("user_mgs_transaction")]
        public SystemUser user_mgs_transaction {
            get {
                return GetRelatedEntity<SystemUser>("user_mgs_transaction", null);
            }
            set {
                SetRelatedEntity("user_mgs_transaction", null, value);
            }
        }
        
        public static mgs_Transaction Retrieve(IOrganizationService service, Guid id, params Expression<Func<mgs_Transaction,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
    
    [DataContract()]
    public enum mgs_TransactionState {
        
        [EnumMember()]
        [OptionSetMetadata("Active", Index=0, Lcid=1033)]
        Active = 0,
        
        [EnumMember()]
        [OptionSetMetadata("Inactive", Index=1, Lcid=1033)]
        Inactive = 1,
    }
    
    [DataContract()]
    public enum mgs_Transaction_statuscode {
        
        [EnumMember()]
        [OptionSetMetadata("Active", Index=0, Lcid=1033)]
        Active = 1,
        
        [EnumMember()]
        [OptionSetMetadata("Inactive", Index=1, Lcid=1033)]
        Inactive = 2,
    }
}
