//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace XrmBedrock.SharedContext {
    
    
    /// <summary>
    /// <para>Entity description</para>
    /// <para>Display Name: Subscription</para>
    /// </summary>
    [EntityLogicalName("mgs_subscription")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class mgs_Subscription : ExtendedEntity<mgs_SubscriptionState, mgs_Subscription_statuscode> {
        
        public const string EntityLogicalName = "mgs_subscription";
        
        public const int EntityTypeCode = 11060;
        
        public mgs_Subscription() : 
                base(EntityLogicalName) {
        }
        
        public mgs_Subscription(Guid Id) : 
                base(EntityLogicalName, Id) {
        }
        
        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay("mgs_subscriptionname");
            }
        }
        
        [AttributeLogicalName("mgs_subscriptionid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("mgs_subscriptionid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for entity instances</para>
        /// <para>Display Name: Subscription</para>
        /// </summary>
        [AttributeLogicalName("mgs_subscriptionid")]
        [DisplayName("Subscription")]
        public Guid? mgs_SubscriptionId {
            get {
                return GetAttributeValue<Guid?>("mgs_subscriptionid");
            }
            set {
                SetId("mgs_subscriptionid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who created the record.</para>
        /// <para>Display Name: Created By</para>
        /// </summary>
        [AttributeLogicalName("createdby")]
        [DisplayName("Created By")]
        public EntityReference CreatedBy {
            get {
                return GetAttributeValue<EntityReference>("createdby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the record was created.</para>
        /// <para>Display Name: Created On</para>
        /// </summary>
        [AttributeLogicalName("createdon")]
        [DisplayName("Created On")]
        public DateTime? CreatedOn {
            get {
                return GetAttributeValue<DateTime?>("createdon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who created the record.</para>
        /// <para>Display Name: Created By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfby")]
        [DisplayName("Created By (Delegate)")]
        public EntityReference CreatedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("createdonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Sequence number of the import that created this record.</para>
        /// <para>Display Name: Import Sequence Number</para>
        /// </summary>
        [AttributeLogicalName("importsequencenumber")]
        [DisplayName("Import Sequence Number")]
        [Range(-2147483648, 2147483647)]
        public int? ImportSequenceNumber {
            get {
                return GetAttributeValue<int?>("importsequencenumber");
            }
            set {
                SetAttributeValue("importsequencenumber", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who modified the record.</para>
        /// <para>Display Name: Modified By</para>
        /// </summary>
        [AttributeLogicalName("modifiedby")]
        [DisplayName("Modified By")]
        public EntityReference ModifiedBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the record was modified.</para>
        /// <para>Display Name: Modified On</para>
        /// </summary>
        [AttributeLogicalName("modifiedon")]
        [DisplayName("Modified On")]
        public DateTime? ModifiedOn {
            get {
                return GetAttributeValue<DateTime?>("modifiedon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who modified the record.</para>
        /// <para>Display Name: Modified By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfby")]
        [DisplayName("Modified By (Delegate)")]
        public EntityReference ModifiedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Date and time that the record was migrated.</para>
        /// <para>Display Name: Record Created On</para>
        /// </summary>
        [AttributeLogicalName("overriddencreatedon")]
        [DisplayName("Record Created On")]
        public DateTime? OverriddenCreatedOn {
            get {
                return GetAttributeValue<DateTime?>("overriddencreatedon");
            }
            set {
                SetAttributeValue("overriddencreatedon", value);
            }
        }
        
        /// <summary>
        /// <para>Owner Id</para>
        /// <para>Display Name: Owner</para>
        /// </summary>
        [AttributeLogicalName("ownerid")]
        [DisplayName("Owner")]
        public EntityReference OwnerId {
            get {
                return GetAttributeValue<EntityReference>("ownerid");
            }
            set {
                SetAttributeValue("ownerid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the business unit that owns the record</para>
        /// <para>Display Name: Owning Business Unit</para>
        /// </summary>
        [AttributeLogicalName("owningbusinessunit")]
        [DisplayName("Owning Business Unit")]
        public EntityReference OwningBusinessUnit {
            get {
                return GetAttributeValue<EntityReference>("owningbusinessunit");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the team that owns the record.</para>
        /// <para>Display Name: Owning Team</para>
        /// </summary>
        [AttributeLogicalName("owningteam")]
        [DisplayName("Owning Team")]
        public EntityReference OwningTeam {
            get {
                return GetAttributeValue<EntityReference>("owningteam");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the user that owns the record.</para>
        /// <para>Display Name: Owning User</para>
        /// </summary>
        [AttributeLogicalName("owninguser")]
        [DisplayName("Owning User")]
        public EntityReference OwningUser {
            get {
                return GetAttributeValue<EntityReference>("owninguser");
            }
        }
        
        /// <summary>
        /// <para>Display Name: Subscription Name</para>
        /// </summary>
        [AttributeLogicalName("mgs_subscriptionname")]
        [DisplayName("Subscription Name")]
        [MaxLength(850)]
        public string PrimaryNameField {
            get {
                return GetAttributeValue<string>("mgs_subscriptionname");
            }
            set {
                SetAttributeValue("mgs_subscriptionname", value);
            }
        }
        
        /// <summary>
        /// <para>For internal use only.</para>
        /// <para>Display Name: Time Zone Rule Version Number</para>
        /// </summary>
        [AttributeLogicalName("timezoneruleversionnumber")]
        [DisplayName("Time Zone Rule Version Number")]
        [Range(-1, 2147483647)]
        public int? TimeZoneRuleVersionNumber {
            get {
                return GetAttributeValue<int?>("timezoneruleversionnumber");
            }
            set {
                SetAttributeValue("timezoneruleversionnumber", value);
            }
        }
        
        /// <summary>
        /// <para>Time zone code that was in use when the record was created.</para>
        /// <para>Display Name: UTC Conversion Time Zone Code</para>
        /// </summary>
        [AttributeLogicalName("utcconversiontimezonecode")]
        [DisplayName("UTC Conversion Time Zone Code")]
        [Range(-1, 2147483647)]
        public int? UTCConversionTimeZoneCode {
            get {
                return GetAttributeValue<int?>("utcconversiontimezonecode");
            }
            set {
                SetAttributeValue("utcconversiontimezonecode", value);
            }
        }
        
        /// <summary>
        /// <para>Version Number</para>
        /// <para>Display Name: Version Number</para>
        /// </summary>
        [AttributeLogicalName("versionnumber")]
        [DisplayName("Version Number")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }
        
        /// <summary>
        /// <para>Display Name: Contact</para>
        /// </summary>
        [AttributeLogicalName("mgs_contact")]
        [DisplayName("Contact")]
        public EntityReference mgs_Contact {
            get {
                return GetAttributeValue<EntityReference>("mgs_contact");
            }
            set {
                SetAttributeValue("mgs_contact", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: End Date</para>
        /// </summary>
        [AttributeLogicalName("mgs_enddate")]
        [DisplayName("End Date")]
        public DateTime? mgs_EndDate {
            get {
                return GetAttributeValue<DateTime?>("mgs_enddate");
            }
            set {
                SetAttributeValue("mgs_enddate", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Invoiced Until</para>
        /// </summary>
        [AttributeLogicalName("mgs_invoiceduntil")]
        [DisplayName("Invoiced Until")]
        public DateTime? mgs_InvoicedUntil {
            get {
                return GetAttributeValue<DateTime?>("mgs_invoiceduntil");
            }
            set {
                SetAttributeValue("mgs_invoiceduntil", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Product</para>
        /// </summary>
        [AttributeLogicalName("mgs_product")]
        [DisplayName("Product")]
        public EntityReference mgs_Product {
            get {
                return GetAttributeValue<EntityReference>("mgs_product");
            }
            set {
                SetAttributeValue("mgs_product", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Start Date</para>
        /// </summary>
        [AttributeLogicalName("mgs_startdate")]
        [DisplayName("Start Date")]
        public DateTime? mgs_StartDate {
            get {
                return GetAttributeValue<DateTime?>("mgs_startdate");
            }
            set {
                SetAttributeValue("mgs_startdate", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Subscription Name</para>
        /// </summary>
        [AttributeLogicalName("mgs_subscriptionname")]
        [DisplayName("Subscription Name")]
        [MaxLength(850)]
        public string mgs_SubscriptionName {
            get {
                return GetAttributeValue<string>("mgs_subscriptionname");
            }
            set {
                SetAttributeValue("mgs_subscriptionname", value);
            }
        }
        
        /// <summary>
        /// <para>Status of the Subscription</para>
        /// <para>Display Name: Status</para>
        /// </summary>
        [AttributeLogicalName("statecode")]
        [DisplayName("Status")]
        public mgs_SubscriptionState? statecode {
            get {
                return GetOptionSetValue<mgs_SubscriptionState>("statecode");
            }
            set {
                SetOptionSetValue("statecode", value);
            }
        }
        
        /// <summary>
        /// <para>Reason for the status of the Subscription</para>
        /// <para>Display Name: Status Reason</para>
        /// </summary>
        [AttributeLogicalName("statuscode")]
        [DisplayName("Status Reason")]
        public mgs_Subscription_statuscode? statuscode {
            get {
                return GetOptionSetValue<mgs_Subscription_statuscode>("statuscode");
            }
            set {
                SetOptionSetValue("statuscode", value);
            }
        }
        
        [AttributeLogicalName("createdby")]
        [RelationshipSchemaName("lk_mgs_subscription_createdby")]
        public SystemUser lk_mgs_subscription_createdby {
            get {
                return GetRelatedEntity<SystemUser>("lk_mgs_subscription_createdby", null);
            }
            set {
                SetRelatedEntity("lk_mgs_subscription_createdby", null, value);
            }
        }
        
        [AttributeLogicalName("createdonbehalfby")]
        [RelationshipSchemaName("lk_mgs_subscription_createdonbehalfby")]
        public SystemUser lk_mgs_subscription_createdonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_mgs_subscription_createdonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_mgs_subscription_createdonbehalfby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedby")]
        [RelationshipSchemaName("lk_mgs_subscription_modifiedby")]
        public SystemUser lk_mgs_subscription_modifiedby {
            get {
                return GetRelatedEntity<SystemUser>("lk_mgs_subscription_modifiedby", null);
            }
            set {
                SetRelatedEntity("lk_mgs_subscription_modifiedby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedonbehalfby")]
        [RelationshipSchemaName("lk_mgs_subscription_modifiedonbehalfby")]
        public SystemUser lk_mgs_subscription_modifiedonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_mgs_subscription_modifiedonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_mgs_subscription_modifiedonbehalfby", null, value);
            }
        }
        
        [AttributeLogicalName("mgs_contact")]
        [RelationshipSchemaName("mgs_subscription_Contact_contact")]
        public Contact mgs_subscription_Contact_contact {
            get {
                return GetRelatedEntity<Contact>("mgs_subscription_Contact_contact", null);
            }
            set {
                SetRelatedEntity("mgs_subscription_Contact_contact", null, value);
            }
        }
        
        [AttributeLogicalName("mgs_product")]
        [RelationshipSchemaName("mgs_subscription_Product_mgs_product")]
        public mgs_Product mgs_subscription_Product_mgs_product {
            get {
                return GetRelatedEntity<mgs_Product>("mgs_subscription_Product_mgs_product", null);
            }
            set {
                SetRelatedEntity("mgs_subscription_Product_mgs_product", null, value);
            }
        }
        
        [RelationshipSchemaName("mgs_transaction_Subscription_mgs_subscription")]
        public IEnumerable<mgs_Transaction> mgs_transaction_Subscription_mgs_subscription {
            get {
                return GetRelatedEntities<mgs_Transaction>("mgs_transaction_Subscription_mgs_subscription", null);
            }
            set {
                SetRelatedEntities("mgs_transaction_Subscription_mgs_subscription", null, value);
            }
        }
        
        [AttributeLogicalName("owninguser")]
        [RelationshipSchemaName("user_mgs_subscription")]
        public SystemUser user_mgs_subscription {
            get {
                return GetRelatedEntity<SystemUser>("user_mgs_subscription", null);
            }
            set {
                SetRelatedEntity("user_mgs_subscription", null, value);
            }
        }
        
        public static mgs_Subscription Retrieve(IOrganizationService service, Guid id, params Expression<Func<mgs_Subscription,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
    
    [DataContract()]
    public enum mgs_SubscriptionState {
        
        [EnumMember()]
        [OptionSetMetadata("Active", Index=0, Lcid=1033)]
        Active = 0,
        
        [EnumMember()]
        [OptionSetMetadata("Inactive", Index=1, Lcid=1033)]
        Inactive = 1,
    }
    
    [DataContract()]
    public enum mgs_Subscription_statuscode {
        
        [EnumMember()]
        [OptionSetMetadata("Active", Index=0, Lcid=1033)]
        Active = 1,
        
        [EnumMember()]
        [OptionSetMetadata("Inactive", Index=1, Lcid=1033)]
        Inactive = 2,
    }
}
