//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace XrmBedrock.SharedContext {
    
    
    /// <summary>
    /// <para>Display Name: Invoice Collection</para>
    /// </summary>
    [EntityLogicalName("mgs_invoicecollection")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class mgs_InvoiceCollection : ExtendedEntity<mgs_InvoiceCollectionState, mgs_InvoiceCollection_statuscode> {
        
        public const string EntityLogicalName = "mgs_invoicecollection";
        
        public const int EntityTypeCode = 11051;
        
        public mgs_InvoiceCollection() : 
                base(EntityLogicalName) {
        }
        
        public mgs_InvoiceCollection(Guid Id) : 
                base(EntityLogicalName, Id) {
        }
        
        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay("mgs_name");
            }
        }
        
        [AttributeLogicalName("mgs_invoicecollectionid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("mgs_invoicecollectionid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for entity instances</para>
        /// <para>Display Name: Invoice Collection</para>
        /// </summary>
        [AttributeLogicalName("mgs_invoicecollectionid")]
        [DisplayName("Invoice Collection")]
        public Guid? mgs_InvoiceCollectionId {
            get {
                return GetAttributeValue<Guid?>("mgs_invoicecollectionid");
            }
            set {
                SetId("mgs_invoicecollectionid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who created the record.</para>
        /// <para>Display Name: Created By</para>
        /// </summary>
        [AttributeLogicalName("createdby")]
        [DisplayName("Created By")]
        public EntityReference CreatedBy {
            get {
                return GetAttributeValue<EntityReference>("createdby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the record was created.</para>
        /// <para>Display Name: Created On</para>
        /// </summary>
        [AttributeLogicalName("createdon")]
        [DisplayName("Created On")]
        public DateTime? CreatedOn {
            get {
                return GetAttributeValue<DateTime?>("createdon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who created the record.</para>
        /// <para>Display Name: Created By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfby")]
        [DisplayName("Created By (Delegate)")]
        public EntityReference CreatedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("createdonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Sequence number of the import that created this record.</para>
        /// <para>Display Name: Import Sequence Number</para>
        /// </summary>
        [AttributeLogicalName("importsequencenumber")]
        [DisplayName("Import Sequence Number")]
        [Range(-2147483648, 2147483647)]
        public int? ImportSequenceNumber {
            get {
                return GetAttributeValue<int?>("importsequencenumber");
            }
            set {
                SetAttributeValue("importsequencenumber", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who modified the record.</para>
        /// <para>Display Name: Modified By</para>
        /// </summary>
        [AttributeLogicalName("modifiedby")]
        [DisplayName("Modified By")]
        public EntityReference ModifiedBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the record was modified.</para>
        /// <para>Display Name: Modified On</para>
        /// </summary>
        [AttributeLogicalName("modifiedon")]
        [DisplayName("Modified On")]
        public DateTime? ModifiedOn {
            get {
                return GetAttributeValue<DateTime?>("modifiedon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who modified the record.</para>
        /// <para>Display Name: Modified By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfby")]
        [DisplayName("Modified By (Delegate)")]
        public EntityReference ModifiedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Date and time that the record was migrated.</para>
        /// <para>Display Name: Record Created On</para>
        /// </summary>
        [AttributeLogicalName("overriddencreatedon")]
        [DisplayName("Record Created On")]
        public DateTime? OverriddenCreatedOn {
            get {
                return GetAttributeValue<DateTime?>("overriddencreatedon");
            }
            set {
                SetAttributeValue("overriddencreatedon", value);
            }
        }
        
        /// <summary>
        /// <para>Owner Id</para>
        /// <para>Display Name: Owner</para>
        /// </summary>
        [AttributeLogicalName("ownerid")]
        [DisplayName("Owner")]
        public EntityReference OwnerId {
            get {
                return GetAttributeValue<EntityReference>("ownerid");
            }
            set {
                SetAttributeValue("ownerid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the business unit that owns the record</para>
        /// <para>Display Name: Owning Business Unit</para>
        /// </summary>
        [AttributeLogicalName("owningbusinessunit")]
        [DisplayName("Owning Business Unit")]
        public EntityReference OwningBusinessUnit {
            get {
                return GetAttributeValue<EntityReference>("owningbusinessunit");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the team that owns the record.</para>
        /// <para>Display Name: Owning Team</para>
        /// </summary>
        [AttributeLogicalName("owningteam")]
        [DisplayName("Owning Team")]
        public EntityReference OwningTeam {
            get {
                return GetAttributeValue<EntityReference>("owningteam");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the user that owns the record.</para>
        /// <para>Display Name: Owning User</para>
        /// </summary>
        [AttributeLogicalName("owninguser")]
        [DisplayName("Owning User")]
        public EntityReference OwningUser {
            get {
                return GetAttributeValue<EntityReference>("owninguser");
            }
        }
        
        /// <summary>
        /// <para>Display Name: Name</para>
        /// </summary>
        [AttributeLogicalName("mgs_name")]
        [DisplayName("Name")]
        [MaxLength(850)]
        public string PrimaryNameField {
            get {
                return GetAttributeValue<string>("mgs_name");
            }
            set {
                SetAttributeValue("mgs_name", value);
            }
        }
        
        /// <summary>
        /// <para>For internal use only.</para>
        /// <para>Display Name: Time Zone Rule Version Number</para>
        /// </summary>
        [AttributeLogicalName("timezoneruleversionnumber")]
        [DisplayName("Time Zone Rule Version Number")]
        [Range(-1, 2147483647)]
        public int? TimeZoneRuleVersionNumber {
            get {
                return GetAttributeValue<int?>("timezoneruleversionnumber");
            }
            set {
                SetAttributeValue("timezoneruleversionnumber", value);
            }
        }
        
        /// <summary>
        /// <para>Time zone code that was in use when the record was created.</para>
        /// <para>Display Name: UTC Conversion Time Zone Code</para>
        /// </summary>
        [AttributeLogicalName("utcconversiontimezonecode")]
        [DisplayName("UTC Conversion Time Zone Code")]
        [Range(-1, 2147483647)]
        public int? UTCConversionTimeZoneCode {
            get {
                return GetAttributeValue<int?>("utcconversiontimezonecode");
            }
            set {
                SetAttributeValue("utcconversiontimezonecode", value);
            }
        }
        
        /// <summary>
        /// <para>Version Number</para>
        /// <para>Display Name: Version Number</para>
        /// </summary>
        [AttributeLogicalName("versionnumber")]
        [DisplayName("Version Number")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }
        
        /// <summary>
        /// <para>Display Name: Invoice Until</para>
        /// </summary>
        [AttributeLogicalName("mgs_invoiceuntil")]
        [DisplayName("Invoice Until")]
        public DateTime? mgs_InvoiceUntil {
            get {
                return GetAttributeValue<DateTime?>("mgs_invoiceuntil");
            }
            set {
                SetAttributeValue("mgs_invoiceuntil", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Name</para>
        /// </summary>
        [AttributeLogicalName("mgs_name")]
        [DisplayName("Name")]
        [MaxLength(850)]
        public string mgs_Name {
            get {
                return GetAttributeValue<string>("mgs_name");
            }
            set {
                SetAttributeValue("mgs_name", value);
            }
        }
        
        /// <summary>
        /// <para>Status of the Invoice Collection</para>
        /// <para>Display Name: Status</para>
        /// </summary>
        [AttributeLogicalName("statecode")]
        [DisplayName("Status")]
        public mgs_InvoiceCollectionState? statecode {
            get {
                return GetOptionSetValue<mgs_InvoiceCollectionState>("statecode");
            }
            set {
                SetOptionSetValue("statecode", value);
            }
        }
        
        /// <summary>
        /// <para>Reason for the status of the Invoice Collection</para>
        /// <para>Display Name: Status Reason</para>
        /// </summary>
        [AttributeLogicalName("statuscode")]
        [DisplayName("Status Reason")]
        public mgs_InvoiceCollection_statuscode? statuscode {
            get {
                return GetOptionSetValue<mgs_InvoiceCollection_statuscode>("statuscode");
            }
            set {
                SetOptionSetValue("statuscode", value);
            }
        }
        
        [AttributeLogicalName("createdby")]
        [RelationshipSchemaName("lk_mgs_invoicecollection_createdby")]
        public SystemUser lk_mgs_invoicecollection_createdby {
            get {
                return GetRelatedEntity<SystemUser>("lk_mgs_invoicecollection_createdby", null);
            }
            set {
                SetRelatedEntity("lk_mgs_invoicecollection_createdby", null, value);
            }
        }
        
        [AttributeLogicalName("createdonbehalfby")]
        [RelationshipSchemaName("lk_mgs_invoicecollection_createdonbehalfby")]
        public SystemUser lk_mgs_invoicecollection_createdonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_mgs_invoicecollection_createdonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_mgs_invoicecollection_createdonbehalfby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedby")]
        [RelationshipSchemaName("lk_mgs_invoicecollection_modifiedby")]
        public SystemUser lk_mgs_invoicecollection_modifiedby {
            get {
                return GetRelatedEntity<SystemUser>("lk_mgs_invoicecollection_modifiedby", null);
            }
            set {
                SetRelatedEntity("lk_mgs_invoicecollection_modifiedby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedonbehalfby")]
        [RelationshipSchemaName("lk_mgs_invoicecollection_modifiedonbehalfby")]
        public SystemUser lk_mgs_invoicecollection_modifiedonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_mgs_invoicecollection_modifiedonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_mgs_invoicecollection_modifiedonbehalfby", null, value);
            }
        }
        
        [RelationshipSchemaName("mgs_invoice_InvoiceCollection_mgs_invoicecollection")]
        public IEnumerable<mgs_Invoice> mgs_invoice_InvoiceCollection_mgs_invoicecollection {
            get {
                return GetRelatedEntities<mgs_Invoice>("mgs_invoice_InvoiceCollection_mgs_invoicecollection", null);
            }
            set {
                SetRelatedEntities("mgs_invoice_InvoiceCollection_mgs_invoicecollection", null, value);
            }
        }
        
        [AttributeLogicalName("owninguser")]
        [RelationshipSchemaName("user_mgs_invoicecollection")]
        public SystemUser user_mgs_invoicecollection {
            get {
                return GetRelatedEntity<SystemUser>("user_mgs_invoicecollection", null);
            }
            set {
                SetRelatedEntity("user_mgs_invoicecollection", null, value);
            }
        }
        
        public static mgs_InvoiceCollection Retrieve(IOrganizationService service, Guid id, params Expression<Func<mgs_InvoiceCollection,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
    
    [DataContract()]
    public enum mgs_InvoiceCollectionState {
        
        [EnumMember()]
        [OptionSetMetadata("Active", Index=0, Lcid=1033)]
        Active = 0,
        
        [EnumMember()]
        [OptionSetMetadata("Inactive", Index=1, Lcid=1033)]
        Inactive = 1,
    }
    
    [DataContract()]
    public enum mgs_InvoiceCollection_statuscode {
        
        [EnumMember()]
        [OptionSetMetadata("Draft", Index=0, Lcid=1033, Description="")]
        Draft = 1,
        
        [EnumMember()]
        [OptionSetMetadata("Inactive", Index=1, Lcid=1033)]
        Inactive = 2,
        
        [EnumMember()]
        [OptionSetMetadata("Create Invoices", Index=2, Lcid=1033, Description="")]
        CreateInvoices = 862810001,
        
        [EnumMember()]
        [OptionSetMetadata("Invoices Created", Index=3, Lcid=1033, Description="")]
        InvoicesCreated = 862810002,
    }
}
