//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace XrmBedrock.SharedContext {
    
    
    [EntityLogicalName("queuemembership")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class QueueMembership : ExtendedEntity<EmptyEnum, EmptyEnum> {
        
        public const string EntityLogicalName = "queuemembership";
        
        public const string RelationshipSchemaName = "QueueMembership";
        
        public const int EntityTypeCode = 1213;
        
        public QueueMembership() : 
                base(EntityLogicalName) {
        }
        
        public QueueMembership(Guid Id) : 
                base(EntityLogicalName, Id) {
        }
        
        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay(null);
            }
        }
        
        [AttributeLogicalName("queuemembershipid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("queuemembershipid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the queue membership.</para>
        /// </summary>
        [AttributeLogicalName("queuemembershipid")]
        public Guid? QueueMembershipId {
            get {
                return GetAttributeValue<Guid?>("queuemembershipid");
            }
            set {
                SetId("queuemembershipid", value);
            }
        }
        
        [AttributeLogicalName("queueid")]
        public Guid? QueueId {
            get {
                return GetAttributeValue<Guid?>("queueid");
            }
        }
        
        [AttributeLogicalName("systemuserid")]
        public Guid? SystemUserId {
            get {
                return GetAttributeValue<Guid?>("systemuserid");
            }
        }
        
        [AttributeLogicalName("versionnumber")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }
        
        public static QueueMembership Retrieve(IOrganizationService service, Guid id, params Expression<Func<QueueMembership,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
}
