//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace XrmBedrock.SharedContext {
    
    
    /// <summary>
    /// <para>A list of records that require action, such as accounts, activities, and cases.</para>
    /// <para>Display Name: Queue</para>
    /// </summary>
    [EntityLogicalName("queue")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class Queue : ExtendedEntity<QueueState, Queue_StatusCode> {
        
        public const string EntityLogicalName = "queue";
        
        public const int EntityTypeCode = 2020;
        
        public Queue() : 
                base(EntityLogicalName) {
        }
        
        public Queue(Guid Id) : 
                base(EntityLogicalName, Id) {
        }
        
        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay("name");
            }
        }
        
        [AttributeLogicalName("queueid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("queueid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the queue.</para>
        /// <para>Display Name: Queue</para>
        /// </summary>
        [AttributeLogicalName("queueid")]
        [DisplayName("Queue")]
        public Guid? QueueId {
            get {
                return GetAttributeValue<Guid?>("queueid");
            }
            set {
                SetId("queueid", value);
            }
        }
        
        /// <summary>
        /// <para>This attribute is no longer used. The data is now in the Mailbox.AllowEmailConnectorToUseCredentials attribute.</para>
        /// <para>Display Name: Allow to Use Credentials for Email Processing (Obsolete)</para>
        /// </summary>
        [AttributeLogicalName("allowemailcredentials")]
        [DisplayName("Allow to Use Credentials for Email Processing (Obsolete)")]
        public bool? AllowEmailCredentials {
            get {
                return GetAttributeValue<bool?>("allowemailcredentials");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the business unit with which the queue is associated.</para>
        /// <para>Display Name: Business Unit</para>
        /// </summary>
        [AttributeLogicalName("businessunitid")]
        [DisplayName("Business Unit")]
        public EntityReference BusinessUnitId {
            get {
                return GetAttributeValue<EntityReference>("businessunitid");
            }
            set {
                SetAttributeValue("businessunitid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who created the queue record.</para>
        /// <para>Display Name: Created By</para>
        /// </summary>
        [AttributeLogicalName("createdby")]
        [DisplayName("Created By")]
        public EntityReference CreatedBy {
            get {
                return GetAttributeValue<EntityReference>("createdby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the queue was created.</para>
        /// <para>Display Name: Created On</para>
        /// </summary>
        [AttributeLogicalName("createdon")]
        [DisplayName("Created On")]
        public DateTime? CreatedOn {
            get {
                return GetAttributeValue<DateTime?>("createdon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who created the queue.</para>
        /// <para>Display Name: Created By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfby")]
        [DisplayName("Created By (Delegate)")]
        public EntityReference CreatedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("createdonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Select the mailbox associated with this queue.</para>
        /// <para>Display Name: Mailbox</para>
        /// </summary>
        [AttributeLogicalName("defaultmailbox")]
        [DisplayName("Mailbox")]
        public EntityReference DefaultMailbox {
            get {
                return GetAttributeValue<EntityReference>("defaultmailbox");
            }
        }
        
        /// <summary>
        /// <para>Description of the queue.</para>
        /// <para>Display Name: Description</para>
        /// </summary>
        [AttributeLogicalName("description")]
        [DisplayName("Description")]
        public string Description {
            get {
                return GetAttributeValue<string>("description");
            }
            set {
                SetAttributeValue("description", value);
            }
        }
        
        /// <summary>
        /// <para>Email address that is associated with the queue.</para>
        /// <para>Display Name: Incoming Email</para>
        /// </summary>
        [AttributeLogicalName("emailaddress")]
        [DisplayName("Incoming Email")]
        [MaxLength(100)]
        public string EMailAddress {
            get {
                return GetAttributeValue<string>("emailaddress");
            }
            set {
                SetAttributeValue("emailaddress", value);
            }
        }
        
        /// <summary>
        /// <para>This attribute is no longer used. The data is now in the Mailbox.Password attribute.</para>
        /// <para>Display Name: Password (Obsolete)</para>
        /// </summary>
        [AttributeLogicalName("emailpassword")]
        [DisplayName("Password (Obsolete)")]
        [MaxLength(200)]
        public string EmailPassword {
            get {
                return GetAttributeValue<string>("emailpassword");
            }
        }
        
        /// <summary>
        /// <para>Shows the status of the primary email address.</para>
        /// <para>Display Name: Primary Email Status</para>
        /// </summary>
        [AttributeLogicalName("emailrouteraccessapproval")]
        [DisplayName("Primary Email Status")]
        public Queue_EmailRouterAccessApproval? EmailRouterAccessApproval {
            get {
                return GetOptionSetValue<Queue_EmailRouterAccessApproval>("emailrouteraccessapproval");
            }
            set {
                SetOptionSetValue("emailrouteraccessapproval", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Email Signature</para>
        /// </summary>
        [AttributeLogicalName("emailsignature")]
        [DisplayName("Email Signature")]
        public EntityReference EmailSignature {
            get {
                return GetAttributeValue<EntityReference>("emailsignature");
            }
            set {
                SetAttributeValue("emailsignature", value);
            }
        }
        
        /// <summary>
        /// <para>This attribute is no longer used. The data is now in the Mailbox.UserName attribute.</para>
        /// <para>Display Name: User Name (Obsolete)</para>
        /// </summary>
        [AttributeLogicalName("emailusername")]
        [DisplayName("User Name (Obsolete)")]
        [MaxLength(200)]
        public string EmailUsername {
            get {
                return GetAttributeValue<string>("emailusername");
            }
        }
        
        /// <summary>
        /// <para>For internal use only.</para>
        /// <para>Display Name: Entity Image Id</para>
        /// </summary>
        [AttributeLogicalName("entityimageid")]
        [DisplayName("Entity Image Id")]
        public Guid? EntityImageId {
            get {
                return GetAttributeValue<Guid?>("entityimageid");
            }
        }
        
        /// <summary>
        /// <para>Exchange rate for the currency associated with the queue with respect to the base currency.</para>
        /// <para>Display Name: Exchange Rate</para>
        /// </summary>
        [AttributeLogicalName("exchangerate")]
        [DisplayName("Exchange Rate")]
        public decimal? ExchangeRate {
            get {
                return GetAttributeValue<decimal?>("exchangerate");
            }
        }
        
        /// <summary>
        /// <para>Information that specifies whether a queue is to ignore unsolicited email (deprecated).</para>
        /// <para>Display Name: Convert To Email Activities</para>
        /// </summary>
        [AttributeLogicalName("ignoreunsolicitedemail")]
        [DisplayName("Convert To Email Activities")]
        public bool? IgnoreUnsolicitedEmail {
            get {
                return GetAttributeValue<bool?>("ignoreunsolicitedemail");
            }
            set {
                SetAttributeValue("ignoreunsolicitedemail", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the data import or data migration that created this record.</para>
        /// <para>Display Name: Import Sequence Number</para>
        /// </summary>
        [AttributeLogicalName("importsequencenumber")]
        [DisplayName("Import Sequence Number")]
        [Range(-2147483648, 2147483647)]
        public int? ImportSequenceNumber {
            get {
                return GetAttributeValue<int?>("importsequencenumber");
            }
            set {
                SetAttributeValue("importsequencenumber", value);
            }
        }
        
        /// <summary>
        /// <para>Incoming email delivery method for the queue.</para>
        /// <para>Display Name: Incoming Email Delivery Method</para>
        /// </summary>
        [AttributeLogicalName("incomingemaildeliverymethod")]
        [DisplayName("Incoming Email Delivery Method")]
        public Queue_IncomingEmailDeliveryMethod? IncomingEmailDeliveryMethod {
            get {
                return GetOptionSetValue<Queue_IncomingEmailDeliveryMethod>("incomingemaildeliverymethod");
            }
            set {
                SetOptionSetValue("incomingemaildeliverymethod", value);
            }
        }
        
        /// <summary>
        /// <para>Convert Incoming Email To Activities</para>
        /// <para>Display Name: Convert Incoming Email To Activities</para>
        /// </summary>
        [AttributeLogicalName("incomingemailfilteringmethod")]
        [DisplayName("Convert Incoming Email To Activities")]
        public Queue_IncomingEmailFilteringMethod? IncomingEmailFilteringMethod {
            get {
                return GetOptionSetValue<Queue_IncomingEmailFilteringMethod>("incomingemailfilteringmethod");
            }
            set {
                SetOptionSetValue("incomingemailfilteringmethod", value);
            }
        }
        
        /// <summary>
        /// <para>Shows the status of approval of the email address by O365 Admin.</para>
        /// <para>Display Name: Email Address O365 Admin Approval Status</para>
        /// </summary>
        [AttributeLogicalName("isemailaddressapprovedbyo365admin")]
        [DisplayName("Email Address O365 Admin Approval Status")]
        public bool? IsEmailAddressApprovedByO365Admin {
            get {
                return GetAttributeValue<bool?>("isemailaddressapprovedbyo365admin");
            }
        }
        
        /// <summary>
        /// <para>Indication of whether a queue is the fax delivery queue.</para>
        /// <para>Display Name: Fax Queue</para>
        /// </summary>
        [AttributeLogicalName("isfaxqueue")]
        [DisplayName("Fax Queue")]
        public bool? IsFaxQueue {
            get {
                return GetAttributeValue<bool?>("isfaxqueue");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who last modified the queue.</para>
        /// <para>Display Name: Modified By</para>
        /// </summary>
        [AttributeLogicalName("modifiedby")]
        [DisplayName("Modified By")]
        public EntityReference ModifiedBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the queue was last modified.</para>
        /// <para>Display Name: Modified On</para>
        /// </summary>
        [AttributeLogicalName("modifiedon")]
        [DisplayName("Modified On")]
        public DateTime? ModifiedOn {
            get {
                return GetAttributeValue<DateTime?>("modifiedon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who last modified the queue.</para>
        /// <para>Display Name: Modified By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfby")]
        [DisplayName("Modified By (Delegate)")]
        public EntityReference ModifiedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Name of the queue.</para>
        /// <para>Display Name: Name</para>
        /// </summary>
        [AttributeLogicalName("name")]
        [DisplayName("Name")]
        [MaxLength(200)]
        public string Name {
            get {
                return GetAttributeValue<string>("name");
            }
            set {
                SetAttributeValue("name", value);
            }
        }
        
        /// <summary>
        /// <para>Number of Queue items associated with the queue.</para>
        /// <para>Display Name: Queue Items</para>
        /// </summary>
        [AttributeLogicalName("numberofitems")]
        [DisplayName("Queue Items")]
        [Range(-2147483648, 2147483647)]
        public int? NumberOfItems {
            get {
                return GetAttributeValue<int?>("numberofitems");
            }
        }
        
        /// <summary>
        /// <para>Number of Members associated with the queue.</para>
        /// <para>Display Name: No. of Members</para>
        /// </summary>
        [AttributeLogicalName("numberofmembers")]
        [DisplayName("No. of Members")]
        [Range(-2147483648, 2147483647)]
        public int? NumberOfMembers {
            get {
                return GetAttributeValue<int?>("numberofmembers");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the organization associated with the queue.</para>
        /// <para>Display Name: Organization</para>
        /// </summary>
        [AttributeLogicalName("organizationid")]
        [DisplayName("Organization")]
        public EntityReference OrganizationId {
            get {
                return GetAttributeValue<EntityReference>("organizationid");
            }
        }
        
        /// <summary>
        /// <para>Outgoing email delivery method for the queue.</para>
        /// <para>Display Name: Outgoing Email Delivery Method</para>
        /// </summary>
        [AttributeLogicalName("outgoingemaildeliverymethod")]
        [DisplayName("Outgoing Email Delivery Method")]
        public Queue_OutgoingEmailDeliveryMethod? OutgoingEmailDeliveryMethod {
            get {
                return GetOptionSetValue<Queue_OutgoingEmailDeliveryMethod>("outgoingemaildeliverymethod");
            }
            set {
                SetOptionSetValue("outgoingemaildeliverymethod", value);
            }
        }
        
        /// <summary>
        /// <para>Date and time that the record was migrated.</para>
        /// <para>Display Name: Record Created On</para>
        /// </summary>
        [AttributeLogicalName("overriddencreatedon")]
        [DisplayName("Record Created On")]
        public DateTime? OverriddenCreatedOn {
            get {
                return GetAttributeValue<DateTime?>("overriddencreatedon");
            }
            set {
                SetAttributeValue("overriddencreatedon", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user or team who owns the queue.</para>
        /// <para>Display Name: Owner</para>
        /// </summary>
        [AttributeLogicalName("ownerid")]
        [DisplayName("Owner")]
        public EntityReference OwnerId {
            get {
                return GetAttributeValue<EntityReference>("ownerid");
            }
            set {
                SetAttributeValue("ownerid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the business unit that owns the queue.</para>
        /// <para>Display Name: Owning Business Unit</para>
        /// </summary>
        [AttributeLogicalName("owningbusinessunit")]
        [DisplayName("Owning Business Unit")]
        public EntityReference OwningBusinessUnit {
            get {
                return GetAttributeValue<EntityReference>("owningbusinessunit");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the team who owns the queue.</para>
        /// <para>Display Name: Owning Team</para>
        /// </summary>
        [AttributeLogicalName("owningteam")]
        [DisplayName("Owning Team")]
        public EntityReference OwningTeam {
            get {
                return GetAttributeValue<EntityReference>("owningteam");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who owns the queue.</para>
        /// <para>Display Name: Owning User</para>
        /// </summary>
        [AttributeLogicalName("owninguser")]
        [DisplayName("Owning User")]
        public EntityReference OwningUser {
            get {
                return GetAttributeValue<EntityReference>("owninguser");
            }
        }
        
        /// <summary>
        /// <para>Name of the queue.</para>
        /// <para>Display Name: Name</para>
        /// </summary>
        [AttributeLogicalName("name")]
        [DisplayName("Name")]
        [MaxLength(200)]
        public string PrimaryNameField {
            get {
                return GetAttributeValue<string>("name");
            }
            set {
                SetAttributeValue("name", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the owner of the queue.</para>
        /// <para>Display Name: Owner (deprecated)</para>
        /// </summary>
        [AttributeLogicalName("primaryuserid")]
        [DisplayName("Owner (deprecated)")]
        public EntityReference PrimaryUserId {
            get {
                return GetAttributeValue<EntityReference>("primaryuserid");
            }
            set {
                SetAttributeValue("primaryuserid", value);
            }
        }
        
        /// <summary>
        /// <para>Type of queue that is automatically assigned when a user or queue is created. The type can be public, private, or work in process.</para>
        /// <para>Display Name: Queue Type</para>
        /// </summary>
        [AttributeLogicalName("queuetypecode")]
        [DisplayName("Queue Type")]
        public Queue_QueueTypeCode? QueueTypeCode {
            get {
                return GetOptionSetValue<Queue_QueueTypeCode>("queuetypecode");
            }
        }
        
        /// <summary>
        /// <para>Select whether the queue is public or private. A public queue can be viewed by all. A private queue can be viewed only by the members added to the queue.</para>
        /// <para>Display Name: Type</para>
        /// </summary>
        [AttributeLogicalName("queueviewtype")]
        [DisplayName("Type")]
        public Queue_QueueViewType? QueueViewType {
            get {
                return GetOptionSetValue<Queue_QueueViewType>("queueviewtype");
            }
            set {
                SetOptionSetValue("queueviewtype", value);
            }
        }
        
        /// <summary>
        /// <para>Status of the queue.</para>
        /// <para>Display Name: Status</para>
        /// </summary>
        [AttributeLogicalName("statecode")]
        [DisplayName("Status")]
        public QueueState? StateCode {
            get {
                return GetOptionSetValue<QueueState>("statecode");
            }
            set {
                SetOptionSetValue("statecode", value);
            }
        }
        
        /// <summary>
        /// <para>Reason for the status of the queue.</para>
        /// <para>Display Name: Status Reason</para>
        /// </summary>
        [AttributeLogicalName("statuscode")]
        [DisplayName("Status Reason")]
        public Queue_StatusCode? StatusCode {
            get {
                return GetOptionSetValue<Queue_StatusCode>("statuscode");
            }
            set {
                SetOptionSetValue("statuscode", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the currency associated with the queue.</para>
        /// <para>Display Name: Currency</para>
        /// </summary>
        [AttributeLogicalName("transactioncurrencyid")]
        [DisplayName("Currency")]
        public EntityReference TransactionCurrencyId {
            get {
                return GetAttributeValue<EntityReference>("transactioncurrencyid");
            }
            set {
                SetAttributeValue("transactioncurrencyid", value);
            }
        }
        
        /// <summary>
        /// <para>Version number of the queue.</para>
        /// <para>Display Name: Version Number</para>
        /// </summary>
        [AttributeLogicalName("versionnumber")]
        [DisplayName("Version Number")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }
        
        /// <summary>
        /// <para>Link assignment input contract with queue.</para>
        /// <para>Display Name: Assignment Input Contract Id</para>
        /// </summary>
        [AttributeLogicalName("msdyn_assignmentinputcontractid")]
        [DisplayName("Assignment Input Contract Id")]
        public EntityReference msdyn_assignmentinputcontractid {
            get {
                return GetAttributeValue<EntityReference>("msdyn_assignmentinputcontractid");
            }
            set {
                SetAttributeValue("msdyn_assignmentinputcontractid", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Assignment Strategy</para>
        /// </summary>
        [AttributeLogicalName("msdyn_assignmentstrategy")]
        [DisplayName("Assignment Strategy")]
        public msdyn_queueassignmentstrategy? msdyn_assignmentstrategy {
            get {
                return GetOptionSetValue<msdyn_queueassignmentstrategy>("msdyn_assignmentstrategy");
            }
            set {
                SetOptionSetValue("msdyn_assignmentstrategy", value);
            }
        }
        
        /// <summary>
        /// <para>Define overflow rules for work items after it enters queue</para>
        /// <para>Display Name: Inqueue Overflow Ruleset</para>
        /// </summary>
        [AttributeLogicalName("msdyn_inqueueoverflowrulesetid")]
        [DisplayName("Inqueue Overflow Ruleset")]
        public EntityReference msdyn_inqueueoverflowrulesetid {
            get {
                return GetAttributeValue<EntityReference>("msdyn_inqueueoverflowrulesetid");
            }
            set {
                SetAttributeValue("msdyn_inqueueoverflowrulesetid", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: intentfamilyid</para>
        /// </summary>
        [AttributeLogicalName("msdyn_intentfamilyid")]
        [DisplayName("intentfamilyid")]
        public EntityReference msdyn_intentfamilyid {
            get {
                return GetAttributeValue<EntityReference>("msdyn_intentfamilyid");
            }
            set {
                SetAttributeValue("msdyn_intentfamilyid", value);
            }
        }
        
        /// <summary>
        /// <para>Shows whether the queue is set as default or not.</para>
        /// <para>Display Name: Is Default Queue</para>
        /// </summary>
        [AttributeLogicalName("msdyn_isdefaultqueue")]
        [DisplayName("Is Default Queue")]
        public bool? msdyn_isdefaultqueue {
            get {
                return GetAttributeValue<bool?>("msdyn_isdefaultqueue");
            }
            set {
                SetAttributeValue("msdyn_isdefaultqueue", value);
            }
        }
        
        /// <summary>
        /// <para>Shows whether the queue is used as Omnichannel queue for work distribution.</para>
        /// <para>Display Name: Is Omnichannel queue</para>
        /// </summary>
        [AttributeLogicalName("msdyn_isomnichannelqueue")]
        [DisplayName("Is Omnichannel queue")]
        public bool? msdyn_isomnichannelqueue {
            get {
                return GetAttributeValue<bool?>("msdyn_isomnichannelqueue");
            }
            set {
                SetAttributeValue("msdyn_isomnichannelqueue", value);
            }
        }
        
        /// <summary>
        /// <para>Maximum queue size</para>
        /// <para>Display Name: Maximum queue size</para>
        /// </summary>
        [AttributeLogicalName("msdyn_maxqueuesize")]
        [DisplayName("Maximum queue size")]
        [Range(0, 2147483647)]
        public int? msdyn_maxqueuesize {
            get {
                return GetAttributeValue<int?>("msdyn_maxqueuesize");
            }
            set {
                SetAttributeValue("msdyn_maxqueuesize", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for Operating hour associated with Queue</para>
        /// <para>Display Name: Operating Hours</para>
        /// </summary>
        [AttributeLogicalName("msdyn_operatinghourid")]
        [DisplayName("Operating Hours")]
        public EntityReference msdyn_operatinghourid {
            get {
                return GetAttributeValue<EntityReference>("msdyn_operatinghourid");
            }
            set {
                SetAttributeValue("msdyn_operatinghourid", value);
            }
        }
        
        /// <summary>
        /// <para>Setting to enable/disable periodic processing of a queue</para>
        /// <para>Display Name: Enable Operating Hours Based Assignment for Queue</para>
        /// </summary>
        [AttributeLogicalName("msdyn_operatinghoursbasedassignment")]
        [DisplayName("Enable Operating Hours Based Assignment for Queue")]
        public bool? msdyn_operatinghoursbasedassignment {
            get {
                return GetAttributeValue<bool?>("msdyn_operatinghoursbasedassignment");
            }
            set {
                SetAttributeValue("msdyn_operatinghoursbasedassignment", value);
            }
        }
        
        /// <summary>
        /// <para>Define overflow rules for work items before it enters queue</para>
        /// <para>Display Name: Prequeue Overflow Ruleset</para>
        /// </summary>
        [AttributeLogicalName("msdyn_prequeueoverflowrulesetid")]
        [DisplayName("Prequeue Overflow Ruleset")]
        public EntityReference msdyn_prequeueoverflowrulesetid {
            get {
                return GetAttributeValue<EntityReference>("msdyn_prequeueoverflowrulesetid");
            }
            set {
                SetAttributeValue("msdyn_prequeueoverflowrulesetid", value);
            }
        }
        
        /// <summary>
        /// <para>Priority of the queue to indicate conversation assignment order to the agent.</para>
        /// <para>Display Name: Priority</para>
        /// </summary>
        [AttributeLogicalName("msdyn_priority")]
        [DisplayName("Priority")]
        [Range(1, 2147483647)]
        public int? msdyn_priority {
            get {
                return GetAttributeValue<int?>("msdyn_priority");
            }
            set {
                SetAttributeValue("msdyn_priority", value);
            }
        }
        
        /// <summary>
        /// <para>Setting to enable/disable periodic processing of a queue</para>
        /// <para>Display Name: Enable Periodic Processing of Queue</para>
        /// </summary>
        [AttributeLogicalName("msdyn_processqueueperiodically")]
        [DisplayName("Enable Periodic Processing of Queue")]
        public bool? msdyn_processqueueperiodically {
            get {
                return GetAttributeValue<bool?>("msdyn_processqueueperiodically");
            }
            set {
                SetAttributeValue("msdyn_processqueueperiodically", value);
            }
        }
        
        /// <summary>
        /// <para>Defines the type of channels handled by this queue</para>
        /// <para>Display Name: Queue type</para>
        /// </summary>
        [AttributeLogicalName("msdyn_queuetype")]
        [DisplayName("Queue type")]
        public msdyn_queuetype? msdyn_queuetype {
            get {
                return GetOptionSetValue<msdyn_queuetype>("msdyn_queuetype");
            }
            set {
                SetOptionSetValue("msdyn_queuetype", value);
            }
        }
        
        /// <summary>
        /// <para>Unique Name for the entity.</para>
        /// <para>Display Name: Unique Name</para>
        /// </summary>
        [AttributeLogicalName("msdyn_uniquename")]
        [DisplayName("Unique Name")]
        [MaxLength(128)]
        public string msdyn_uniquename {
            get {
                return GetAttributeValue<string>("msdyn_uniquename");
            }
            set {
                SetAttributeValue("msdyn_uniquename", value);
            }
        }
        
        [AttributeLogicalName("createdonbehalfby")]
        [RelationshipSchemaName("lk_queue_createdonbehalfby")]
        public SystemUser lk_queue_createdonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_queue_createdonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_queue_createdonbehalfby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedonbehalfby")]
        [RelationshipSchemaName("lk_queue_modifiedonbehalfby")]
        public SystemUser lk_queue_modifiedonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_queue_modifiedonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_queue_modifiedonbehalfby", null, value);
            }
        }
        
        [AttributeLogicalName("createdby")]
        [RelationshipSchemaName("lk_queuebase_createdby")]
        public SystemUser lk_queuebase_createdby {
            get {
                return GetRelatedEntity<SystemUser>("lk_queuebase_createdby", null);
            }
            set {
                SetRelatedEntity("lk_queuebase_createdby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedby")]
        [RelationshipSchemaName("lk_queuebase_modifiedby")]
        public SystemUser lk_queuebase_modifiedby {
            get {
                return GetRelatedEntity<SystemUser>("lk_queuebase_modifiedby", null);
            }
            set {
                SetRelatedEntity("lk_queuebase_modifiedby", null, value);
            }
        }
        
        [AttributeLogicalName("primaryuserid")]
        [RelationshipSchemaName("queue_primary_user")]
        public SystemUser queue_primary_user {
            get {
                return GetRelatedEntity<SystemUser>("queue_primary_user", null);
            }
            set {
                SetRelatedEntity("queue_primary_user", null, value);
            }
        }
        
        [RelationshipSchemaName("queue_system_user")]
        public IEnumerable<SystemUser> queue_system_user {
            get {
                return GetRelatedEntities<SystemUser>("queue_system_user", null);
            }
            set {
                SetRelatedEntities("queue_system_user", null, value);
            }
        }
        
        [RelationshipSchemaName("queuemembership_association")]
        public IEnumerable<SystemUser> queuemembership_association {
            get {
                return GetRelatedEntities<SystemUser>("queuemembership_association", null);
            }
            set {
                SetRelatedEntities("queuemembership_association", null, value);
            }
        }
        
        public static Queue Retrieve(IOrganizationService service, Guid id, params Expression<Func<Queue,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
    
    [DataContract()]
    public enum QueueState {
        
        [EnumMember()]
        [OptionSetMetadata("Active", Index=0, Lcid=1033)]
        Active = 0,
        
        [EnumMember()]
        [OptionSetMetadata("Inactive", Index=1, Lcid=1033)]
        Inactive = 1,
    }
    
    [DataContract()]
    public enum Queue_EmailRouterAccessApproval {
        
        [EnumMember()]
        [OptionSetMetadata("Empty", Index=0, Lcid=1033)]
        Empty = 0,
        
        [EnumMember()]
        [OptionSetMetadata("Approved", Index=1, Lcid=1033)]
        Approved = 1,
        
        [EnumMember()]
        [OptionSetMetadata("Pending Approval", Index=2, Lcid=1033)]
        PendingApproval = 2,
        
        [EnumMember()]
        [OptionSetMetadata("Rejected", Index=3, Lcid=1033)]
        Rejected = 3,
    }
    
    [DataContract()]
    public enum Queue_IncomingEmailDeliveryMethod {
        
        [EnumMember()]
        [OptionSetMetadata("None", Index=0, Lcid=1033)]
        None = 0,
        
        [EnumMember()]
        [OptionSetMetadata("Server-Side Synchronization or Email Router", Index=1, Lcid=1033)]
        ServerSideSynchronizationorEmailRouter = 2,
        
        [EnumMember()]
        [OptionSetMetadata("Forward Mailbox", Index=2, Lcid=1033)]
        ForwardMailbox = 3,
    }
    
    [DataContract()]
    public enum Queue_IncomingEmailFilteringMethod {
        
        [EnumMember()]
        [OptionSetMetadata("All email messages", Index=0, Lcid=1033)]
        Allemailmessages = 0,
        
        [EnumMember()]
        [OptionSetMetadata("Email messages in response to Dynamics 365 email", Index=1, Lcid=1033)]
        EmailmessagesinresponsetoDynamics365email = 1,
        
        [EnumMember()]
        [OptionSetMetadata("Email messages from Dynamics 365 Leads, Contacts and Accounts", Index=2, Lcid=1033)]
        EmailmessagesfromDynamics365LeadsContactsandAccounts = 2,
        
        [EnumMember()]
        [OptionSetMetadata("Email messages from Dynamics 365 records that are email enabled", Index=3, Lcid=1033)]
        EmailmessagesfromDynamics365recordsthatareemailenabled = 3,
        
        [EnumMember()]
        [OptionSetMetadata("No email messages", Index=4, Lcid=1033)]
        Noemailmessages = 4,
    }
    
    [DataContract()]
    public enum Queue_OutgoingEmailDeliveryMethod {
        
        [EnumMember()]
        [OptionSetMetadata("None", Index=0, Lcid=1033)]
        None = 0,
        
        [EnumMember()]
        [OptionSetMetadata("Server-Side Synchronization or Email Router", Index=1, Lcid=1033)]
        ServerSideSynchronizationorEmailRouter = 2,
    }
    
    [DataContract()]
    public enum Queue_QueueTypeCode {
        
        [EnumMember()]
        [OptionSetMetadata("Default Value", Index=0, Lcid=1033)]
        DefaultValue = 1,
    }
    
    [DataContract()]
    public enum Queue_QueueViewType {
        
        [EnumMember()]
        [OptionSetMetadata("Public", Index=0, Lcid=1033)]
        Public = 0,
        
        [EnumMember()]
        [OptionSetMetadata("Private", Index=1, Lcid=1033)]
        Private = 1,
    }
    
    [DataContract()]
    public enum Queue_StatusCode {
        
        [EnumMember()]
        [OptionSetMetadata("Active", Index=1, Lcid=1033)]
        Active = 1,
        
        [EnumMember()]
        [OptionSetMetadata("Inactive", Index=0, Lcid=1033)]
        Inactive = 2,
    }
}
