//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace XrmBedrock.SharedContext {
    
    
    public partial class Xrm : ExtendedOrganizationServiceContext {
        
        public Xrm(IOrganizationService service) : 
                base(service) {
        }
        
        public IQueryable<Account> AccountSet {
            get {
                return CreateQuery<Account>();
            }
        }
        
        public IQueryable<Annotation> AnnotationSet {
            get {
                return CreateQuery<Annotation>();
            }
        }
        
        public IQueryable<Contact> ContactSet {
            get {
                return CreateQuery<Contact>();
            }
        }
        
        public IQueryable<DuplicateRule> DuplicateRuleSet {
            get {
                return CreateQuery<DuplicateRule>();
            }
        }
        
        public IQueryable<EnvironmentVariableDefinition> EnvironmentVariableDefinitionSet {
            get {
                return CreateQuery<EnvironmentVariableDefinition>();
            }
        }
        
        public IQueryable<EnvironmentVariableValue> EnvironmentVariableValueSet {
            get {
                return CreateQuery<EnvironmentVariableValue>();
            }
        }
        
        public IQueryable<Queue> QueueSet {
            get {
                return CreateQuery<Queue>();
            }
        }
        
        public IQueryable<QueueMembership> QueueMembershipSet {
            get {
                return CreateQuery<QueueMembership>();
            }
        }
        
        public IQueryable<SavedQuery> SavedQuerySet {
            get {
                return CreateQuery<SavedQuery>();
            }
        }
        
        public IQueryable<SystemUser> SystemUserSet {
            get {
                return CreateQuery<SystemUser>();
            }
        }
        
        public IQueryable<Task> TaskSet {
            get {
                return CreateQuery<Task>();
            }
        }
        
        public IQueryable<Template> TemplateSet {
            get {
                return CreateQuery<Template>();
            }
        }
        
        public IQueryable<appnotification> appnotificationSet {
            get {
                return CreateQuery<appnotification>();
            }
        }
        
        public IQueryable<mgs_Invoice> mgs_InvoiceSet {
            get {
                return CreateQuery<mgs_Invoice>();
            }
        }
        
        public IQueryable<mgs_InvoiceCollection> mgs_InvoiceCollectionSet {
            get {
                return CreateQuery<mgs_InvoiceCollection>();
            }
        }
        
        public IQueryable<mgs_Product> mgs_ProductSet {
            get {
                return CreateQuery<mgs_Product>();
            }
        }
        
        public IQueryable<mgs_Subscription> mgs_SubscriptionSet {
            get {
                return CreateQuery<mgs_Subscription>();
            }
        }
        
        public IQueryable<mgs_Transaction> mgs_TransactionSet {
            get {
                return CreateQuery<mgs_Transaction>();
            }
        }
    }
}
