name: 'Setup Build Environment'
description: 'Sets up .NET, Node, signtool, and initializes setup files'
runs:
  using: 'composite'
  steps:
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Setup Node 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Add signtool.exe to path for build
      shell: pwsh
      run: |
        $signtool = Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin\" `
                      -Recurse -Filter signtool.exe `
                      | Where-Object { $_.FullName -match '\\x64\\' } `
                      | Sort-Object LastWriteTime -Descending `
                      | Select-Object -First 1 -ExpandProperty DirectoryName
        if (-not $signtool) {
          throw "signtool.exe (x64) was not found!"
        }
        echo "PATH=$signtool;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "Located signtool at: $signtool"

    - name: Copy Setup files
      shell: pwsh
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        ./Setup/copyInitialSetup.ps1
