parameters:
  environment: ""
  serviceConnectionName: ""
  params: {}

jobs:
  - job: Deploy_WebApp_ExampleApi
    displayName: Deploy Web App Example Api
    dependsOn: Deploy_Infrastructure
    condition: eq(${{parameters.params.deployExampleApi}}, true)
    steps:
      - download: current
        artifact: drop
        displayName: Download drop
      - task: AzureWebApp@1
        displayName: "Deploy Web App"
        retryCountOnTaskFailure: 4
        inputs:
          azureSubscription: ${{ parameters.serviceConnectionName }}
          appName: "app-${{lower(parameters.environment)}}-exampleapi" # Does not exist in codebase - this is just an example
          package: "$(Pipeline.Workspace)/drop/publish/ExampleApi.zip"
