parameters:
  environment:
  serviceConnectionName:
  params:

jobs:
  #Copy this -deployment when deploying to a new function and change:
  #Remember to add a new param to BuildAndDeploy.yaml
  #deployment, displayName, condition, appName, package (#)
  #Added retry because of know bug: https://github.com/microsoft/azure-pipelines-tasks/issues/15532

  - job: Deploy_FunctionApp_EconomyArea
    displayName: Deploy EconomyArea FA
    dependsOn: Deploy_Infrastructure
    condition: eq(${{parameters.params.deployEconomyAreaFA}}, true)
    steps:
      - download: current
        artifact: drop
        displayName: Download drop
      - task: AzureFunctionApp@1
        displayName: "Deploy"
        retryCountOnTaskFailure: 4
        inputs:
          azureSubscription: ${{parameters.serviceConnectionName}}
          appType: functionApp
          appName: "func-economyarea-mgs-demo-${{lower(parameters.environment)}}" #Name is set in main.bicep and depends on your namingSuffix
          package: "$(Pipeline.Workspace)/drop/publish/EconomyAreaFunctionApp.zip"
          appSettings: '-appsettingKey "$(AppSettingValueFromLibrary)"'