<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SharedContext\SharedContext.csproj" />
    <ProjectReference Include="..\..\Shared\SharedDataverseLogic\SharedDataverseLogic.csproj" />
    <ProjectReference Include="..\..\Shared\SharedDomain\SharedDomain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DataverseConnection" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="OneOf" Version="3.0.271" />
	<PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.17" />
  </ItemGroup>
  
</Project>
