name: (child) Deoploy Environment

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      CLIENT_SECRET:
        required: true

jobs:
  deployenvironment:
    runs-on: windows-latest
    environment: ${{ inputs.ENVIRONMENT }}
    env:
      FSI_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools\fsi.exe'
      DAXIF_PATH: 'daxif'
    steps:
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install and configure PAC
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          pac auth create --environment "https://${{ inputs.ENVIRONMENT }}-cin.crm11.dynamics.com" --tenant ${{ vars.TENANT_ID }} --applicationId ${{ vars.DATAVERSE_APP_ID }} --clientSecret ${{ secrets.CLIENT_SECRET }}

      - name: Download DAXIF artifact
        uses: actions/download-artifact@v4
        with:
          name: daxif
          path: daxif

      - name: Download solution artifact
        uses: actions/download-artifact@v4
        with:
          name: solutions
          path: daxif/solutions

      - name: Import solution ${{ inputs.ENVIRONMENT}}
        run: '& "$env:FSI_PATH" $env:DAXIF_PATH/SolutionImportArg.fsx /env=${{ inputs.ENVIRONMENT }} /dir=solutions /mfaAppId="${{ vars.DATAVERSE_APP_ID }}" /mfaClientSecret="${{ secrets.CLIENT_SECRET }}" /method="ClientSecret"'

      - name: Publish all customizations
        run: pac solution publish

      - name: Solution Post Import ${{ inputs.ENVIRONMENT}}
        run: '& "$env:FSI_PATH" $env:DAXIF_PATH/SolutionPostImportArg.fsx /env=${{ inputs.ENVIRONMENT }} /dir=solutions /mfaAppId="${{ vars.DATAVERSE_APP_ID }}" /mfaClientSecret="${{ secrets.CLIENT_SECRET }}" /method="ClientSecret"'
        