name: (child) Package

on:
  workflow_call:
    secrets:
      CLIENT_SECRET:
        required: true

jobs:
  package:
    runs-on: windows-latest
    environment: dev
    env:
      FSI_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools\fsi.exe'
      DAXIF_PATH: 'daxif'
      ENVIRONMENT: 'https://<your-env>-dev.crm4.dynamics.com'
    steps:
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install and configure PAC
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          pac auth create --environment "${{ env.ENVIRONMENT}}" --tenant ${{ vars.TENANT_ID }} --applicationId ${{ vars.DATAVERSE_APP_ID }} --clientSecret ${{ secrets.CLIENT_SECRET }}

      - name: Publish all customizations
        run: pac solution publish

      - name: Download DAXIF artifact
        uses: actions/download-artifact@v4
        with:
          name: daxif
          path: daxif

      - name: Export
        run: '& "$env:FSI_PATH" $env:DAXIF_PATH/SolutionExportDev.fsx /mfaAppId="${{ vars.DATAVERSE_APP_ID }}" /mfaClientSecret="${{ secrets.CLIENT_SECRET }}" /method="ClientSecret"'

      - name: Publish solutions artifact
        uses: actions/upload-artifact@v4
        with:
          name: solutions
          path: ${{ env.DAXIF_PATH }}/solutions
